### ISSUE TITLE
All API methods need to be authenticated against, not just those writing data

### ISSUE THREAD

**Issue by drchristhorpe** [reasondigital/Shared-Service-Layer-Search#1]

**Comment by EjiReason** [comment]
Laravel Sanctum middleware has been implemented on all API routes via the Route Service Provider, thus requiring a token with every request. In the same vein, the `::validatePermission()` method was moved to the top level Controller class.

Relevant commit: https://github.com/reasondigital/Shared-Service-Layer-Search/commit/8c73389897abfcb03151a4b7d000ad261f98ecdb
