### ISSUE TITLE
Geosearch queries relating to a specific place (as opposed to radial/as the crow flies) should be determined on geoshapes rather than fuzzy matching of place names

### ISSUE THREAD

**Issue by drchristhorpe** [reasondigital/Shared-Service-Layer-Search#2]

**Comment by EjiReason** [comment]
The search controller has been updated to accept Polyline as a bounding shape query — the `boundingShape` parameter — and conduct that location search only within the given shape.

Relevant commit: https://github.com/reasondigital/Shared-Service-Layer-Search/commit/20ba36bd45ca3aa36a6bfee36372ea29d45f044b
