### ISSUE TITLE
Some data in the API returns may be sensitive, therefore there should be a mechanism to redact specific fields unless a higher level of user is authenticated

### ISSUE THREAD

**Issue by drchristhorpe** [reasondigital/Shared-Service-Layer-Search#3]

**Comment by EjiReason** [comment]
The Article, Location and Shape controllers have checks for sensitive content on endpoints that retrieve data from the API. This follows work that allows a "sensitive" flag to be set on those entities.

Some relevant commits. These show work on the article model, though there was equivalent work done for the Location and Shape models:

- https://github.com/reasondigital/Shared-Service-Layer-Search/commit/f420855f40c0b288ee033ae17eab08478fb6495a
- https://github.com/reasondigital/Shared-Service-Layer-Search/commit/f7204dae38e17c06b15c867579b326848125c073
